spring.application.name=JWT_springboot3

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=YOUR_DATABASE_NAME;encrypt=false;trustServerCertificate=true

spring.datasource.username=YOUR_DATABASE_USERNAME
spring.datasource.password=YOUR_DATABASE_PASSWORD

## Hibernate properties

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

security.jwt.secret-key=YOUR_JWT_SECRET_KEY

# 1h in millisecond
security.jwt.expiration-time=3600000